const defaults=[
{id:1,name:'Michael Kors Tote Bag',category:'Bags',price:4299,image:'bag.jpg'},
{id:2,name:'Anne Klein Watch',category:'Watches',price:1799,image:'watch.jpg'},
{id:3,name:'Tommy Hilfiger Perfume',category:'Perfume',price:3499,image:'perfume.jpg'},
{id:4,name:'Classic Black Bag',category:'Bags',price:2999,image:'sale_bag.jpg',sale:true},
{id:5,name:'Tommy Casual Shoes',category:'Shoes',price:3899,image:'shoes.jpg',new:true},
{id:6,name:'Daily Vitamins',category:'Vitamins',price:1299,image:'vitamins.jpg',new:true},
{id:7,name:'Designer Wallet',category:'Wallets',price:2199,image:'wallet.jpg',new:true}];
const cats=[['Bags','bag.jpg'],['Wallets','wallet.jpg'],['Perfume','perfume.jpg'],['Shoes','shoes.jpg'],['Vitamins','vitamins.jpg'],['Watches','watch.jpg']];
// Removed: Carol, Alexis Bendel, Karen Neuburger, DCSHOECOUSA, Stone Mountain USA, Vera Wang, Escada, planetGOLD, White Mountain.
const brands='adidas|ALDO|ANNE KLEIN|BEVERLY HILLS POLO CLUB|Calvin Klein|Champion|COLE HAAN|DKNY|GAP|GUESS|HEAD|Herschel|HUGO|IZOD|JORDAN|Juicy Couture|KARL LAGERFELD|kate spade|kipling|LACOSTE|Levi’s|MARC JACOBS|MICHAEL KORS|nanette lepore|NAUTICA|NIKE|NINE WEST|Paris Hilton|Penguin|PERRY ELLIS|PUMA|RALPH LAUREN|Reebok|STEVE MADDEN|TED BAKER|TOMMY HILFIGER|TRUE RELIGION|U.S POLO ASSN.|VAN HEUSEN|WRANGLER|XOXO'.split('|');
let products=JSON.parse(localStorage.getItem('ddProducts')||'null')||defaults;
let cart=JSON.parse(localStorage.getItem('ddCart')||'null')||[{productId:1,qty:2},{productId:2,qty:1},{productId:3,qty:1}];
let filter='dashboard',editId=null,uploaded='';
const page=document.getElementById('page'),money=n=>'₱'+Number(n).toLocaleString('en-PH',{minimumFractionDigits:2});
const save=()=>{localStorage.setItem('ddProducts',JSON.stringify(products));localStorage.setItem('ddCart',JSON.stringify(cart))};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function dashboard(){page.innerHTML=`<section class="hero"><h1>Style Meets<br>Great Deals</h1><p>Authentic Brands. Amazing Prices.</p><button class="pink" onclick="shop()">Shop Now →</button></section><div class="section-head"><h2>Shop by Category</h2><button class="view" onclick="shop()">View All →</button></div><div class="cats">${cats.map(x=>`<button class="cat" onclick="category('${x[0]}')"><img src="${x[1]}" onerror="this.src='bag.jpg'">${x[0]}</button>`).join('')}</div><div class="promos"><div class="promo sale"><h3>FLASH SALE ⚡</h3><p>Up to 70% OFF • Limited time only!</p><button class="shopbtn" onclick="sale()">Shop Now</button><img src="sale_bag.jpg"></div><div class="promo new"><h3>New Arrivals ♥</h3><p>Fresh styles you'll love.</p><button class="shopbtn" onclick="newArrivals()">Discover Now</button><img src="new_shoes.jpg"></div></div><section class="brands"><h2>CHOOSE FROM POPULAR BRANDS</h2><div class="under"></div><div class="brandgrid">${brands.map(b=>`<div class="brand">${b}</div>`).join('')}</div></section>`}
function card(p){let sp=p.salePrice||(p.sale?Math.round(p.price*.7):0);return `<article class="product">${p.sale?'<span class="badge">SALE</span>':p.new?'<span class="badge">NEW</span>':''}<img src="${p.image||'bag.jpg'}" onerror="this.src='bag.jpg'"><div class="info"><h3>${esc(p.name)}</h3><p>${esc(p.category)}</p><span class="price">${money(sp||p.price)} ${sp?`<span class="old">${money(p.price)}</span>`:''}</span><button class="add" onclick="add(${p.id})">+ Add</button></div></article>`}
function listing(title,list){page.innerHTML=`<div class="section-head"><h1 class="page-title">${title}</h1><button class="pink add-product" onclick="openModal()">＋ Add Product</button></div><div class="products">${list.length?list.map(card).join(''):'<div class="empty">No products found.</div>'}</div>`}
function shop(){filter='shop';listing('Shop All',products)} function sale(){filter='sale';listing('Sale Items',products.filter(p=>p.sale))} function newArrivals(){filter='new';listing('New Arrivals',products.filter(p=>p.new))} function category(c){filter=c;listing(c,products.filter(p=>p.category===c))}
function simple(t,msg){page.innerHTML=`<h1 class="page-title">${t}</h1><p class="muted">${msg}</p><div class="empty">This section is ready for your store data.</div>`}
function add(id){let x=cart.find(i=>i.productId===id);x?x.qty++:cart.push({productId:id,qty:1});save();renderCart()}
function qty(id,d){let x=cart.find(i=>i.productId===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(i=>i.productId!==id);save();renderCart()}
function remove(id){cart=cart.filter(i=>i.productId!==id);save();renderCart()}
function renderCart(){let rows=cart.map(i=>({...i,p:products.find(p=>p.id===i.productId)})).filter(x=>x.p);document.getElementById('count').textContent='('+rows.reduce((a,x)=>a+x.qty,0)+')';document.getElementById('cartItems').innerHTML=rows.length?rows.map(x=>`<div class="cart-item"><img src="${x.p.image||'bag.jpg'}" onerror="this.src='bag.jpg'"><div><h4>${esc(x.p.name)}</h4><small>${x.p.category}</small><div class="cart-price">${money(x.p.salePrice||x.p.price)}</div></div><div class="qty"><button onclick="qty(${x.p.id},-1)">−</button>${x.qty}<button onclick="qty(${x.p.id},1)">+</button><button onclick="remove(${x.p.id})">×</button></div></div>`).join(''):'<div class="empty">Your cart is empty.</div>';let total=rows.reduce((a,x)=>a+(x.p.salePrice||x.p.price)*x.qty,0);document.getElementById('subtotal').textContent=money(total);document.getElementById('total').textContent=money(total)}
function openModal(id=null){editId=id;uploaded='';let p=id&&products.find(x=>x.id===id);document.getElementById('modal').classList.remove('hidden');document.getElementById('name').value=p?.name||'';document.getElementById('category').value=p?.category||'Bags';document.getElementById('price').value=p?.price||'';document.getElementById('salePrice').value=p?.salePrice||'';document.getElementById('description').value=p?.description||'';document.getElementById('isNew').checked=!!p?.new;document.getElementById('isSale').checked=!!p?.sale;document.getElementById('preview').src=p?.image||''}
document.getElementById('close').onclick=()=>document.getElementById('modal').classList.add('hidden');
document.getElementById('file').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{uploaded=r.result;document.getElementById('preview').src=uploaded};r.readAsDataURL(f)};
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>document.getElementById('preview').style.filter=b.id==='reset'?'none':b.dataset.f);
document.getElementById('save').onclick=()=>{let name=document.getElementById('name').value.trim(),price=Number(document.getElementById('price').value);if(!name||!price){alert('Enter a product name and price.');return}let old=editId&&products.find(p=>p.id===editId);let p={id:editId||Date.now(),name,category:document.getElementById('category').value,price,salePrice:Number(document.getElementById('salePrice').value)||null,description:document.getElementById('description').value,image:uploaded||old?.image||'bag.jpg',new:document.getElementById('isNew').checked,sale:document.getElementById('isSale').checked};products=editId?products.map(x=>x.id===editId?p:x):[...products,p];save();document.getElementById('modal').classList.add('hidden');filter==='dashboard'?dashboard():filter==='shop'?shop():filter==='sale'?sale():filter==='new'?newArrivals():category(filter)};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');let v=b.dataset.view;v==='dashboard'?dashboard():v==='shop'?shop():v==='sale'?sale():v==='new'?newArrivals():v==='orders'?simple('My Orders','Your previous orders will appear here.'):simple(v[0].toUpperCase()+v.slice(1),'This section is ready for your store data.')});
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');category(b.dataset.cat)});
document.getElementById('logout').onclick=()=>alert('Connect this button to your login system when you add authentication.');document.getElementById('checkout').onclick=()=>alert('Connect Checkout to your payment/order system.');document.getElementById('menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.getElementById('mobileCart').onclick=()=>document.querySelector('.cart').style.display='flex';document.getElementById('cartClose').onclick=()=>document.querySelector('.cart').style.display='none';dashboard();renderCart();
